# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The-Programming-Squirrel
tagline: "Empowering Curious Minds with Nuts of Knowledge in Tech and Cybersecurity!"
description: >
  Empowering Beginners and Women in Cybersecurity with Tutorials, Study Guides, and More.
baseurl: ""
url: "https://the-programming-squirrel.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Details
author:
  name: Nyki Anderson
  avatar: "/assets/images/avatar.png" # Replace with your avatar image
  bio: >
    Passionate cybersecurity advocate, empowering women & beginners with fun, accessible resources to crack the code & thrive in the field! 

defaults:
  - scope:
      path: ""
    values:
      toc: true

########################## Squirrel Theme ##########################
theme: squirrel-theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - premonition
  - jekyll-spaceship
  - jekyll-glossary_tooltip
  - jekyll-toc
  - jekyll-figure

# Premonition custom callouts
premonition:
  types:
    objectives:
      icon: "fa fa-bullseye"
      title: "Objectives"
    tip:
      icon: "fa fa-lightbulb-o"
      title: "Tip"
    quote:
      icon: "fa fa-quote-left"
      title: "Quote"
    resource:
      icon: "fa fa-book"
      title: "Resource"
    recall:
      icon: "fa fa-fast-backward"
      title: "Recall"
