title: The Programming Squirrel
tagline: "Learn, Hack, Thrive: Cybersecurity Made Inclusive."
description: >
  Empowering cybersecurity learners with tutorials, guides, and an inclusive tech community.
keywords: [
  "cybersecurity",
  "ethical hacking",
  "penetration testing",
  "tech tutorials",
  "women in tech",
  "cybersecurity resources",
  "tech trends",
  "programming tutorials",
  "burp suite",
  "comptia security+",
  "kali linux",
  "owasp zap",
  "cybersecurity certification",
  "python for hacking",
  "diversity in tech",
  "digital security blog"
]
baseurl: ""
url: "https://the-programming-squirrel.com" 
permalink: pretty
theme: jekyll-squirrel-theme

# Author Details
author:
  name: Nyki Anderson
  avatar: /assets/avatars/avatar-white-buttonup.png
  bio: >
    Nyki Anderson, founder of The Programming Squirrel, is a cybersecurity expert and advocate for diversity in tech. With a passion for education, Nyki creates engaging tutorials, certification guides, and community-focused resources to empower learners of all levels. Through her blog, she aims to foster inclusivity, provide actionable insights, and inspire the next generation of cybersecurity professionals.

# Squirrel Theme Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-glossary_tooltip
  - jekyll-toc
  - jekyll-figure
  - jekyll-paginate-v2

# Syntax Highlighting
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

jekyll-figure:
  paragraphs: false

pagination:
  enabled: true
  path: "/blog/page:num/"
  per_page: 5
  limit: 0
