title: The-Programming-Squirrel
tagline: "Empowering Beginners and Women in Cybersecurity with Tutorials, Study Guides, and More!"
description: >
  Empowering Beginners and Women in Cybersecurity with Tutorials, Study Guides, and More.
baseurl: ""
url: "https://the-programming-squirrel.com" 
theme: jekyll-squirrel-theme

# Author Details
author:
  name: Nyki Anderson
  avatar: "/assets/images/avatar.png" # Replace with your avatar image
  bio: >
    Passionate cybersecurity advocate, empowering women & beginners with fun, accessible resources to crack the code & thrive in the field! 

defaults:
  - scope:
      path: ""
    values:
      toc: true

# Squirrel Theme Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - premonition
  - jekyll-spaceship
  - jekyll-glossary_tooltip
  - jekyll-toc
  - jekyll-figure

# Premonition custom callouts
premonition:
  types:
    objectives:
      icon: "fa fa-bullseye"
      title: "Objectives"
    tip:
      icon: "fa fa-lightbulb-o"
      title: "Tip"
    quote:
      icon: "fa fa-quote-left"
      title: "Quote"
    resource:
      icon: "fa fa-book"
      title: "Resource"
    recall:
      icon: "fa fa-fast-backward"
      title: "Recall"
