# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The-Programming-Squirrel
description: >
  Empowering Beginners and Women in Cybersecurity with Tutorials, Study Guides, and More.
baseurl: ""
url: "https://the-programming-squirrel.com" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima

# Navigation
header_pages:
  - index.md
  - blog/index.md
  - about/index.md

# Social Links
social:
  email: nyki@the-programming-squirrel.com
  twitter: ProgramSquirrel
  github: The-Programming-Squirrel
  linkedin: nykianderson

# Author Details
author:
  name: Nyki Anderson
  avatar: "/assets/images/avatar.jpg" # Replace with your avatar image
  bio: >
    Passionate cybersecurity advocate, empowering women & beginners with fun, accessible resources to crack the code & thrive in the field! 

# Plugins
plugins:
  - jekyll-feed
