title: The-Programming-Squirrel
tagline: "Empowering Beginners and Women in Cybersecurity with Tutorials, Study Guides, and More!"
description: >
  Empowering Beginners and Women in Cybersecurity with Tutorials, Study Guides, and More.
keywords: ["The Programming Squirrel, cybersecurity, cybersecurity education, cybersecurity tutorials, Burp Suite guide, CompTIA Security+, Kali Linux, ethical hacking, cybersecurity resources, diversity in tech, women in cybersecurity, cybersecurity community, online cybersecurity learning, cybersecurity certification, cybersecurity tips, cybersecurity study guides, cybersecurity quizzes, cybersecurity cheat sheets, beginner cybersecurity, intermediate cybersecurity, cybersecurity blog, cybersecurity tools, cybersecurity career, cybersecurity training, cybersecurity empowerment, ethical hacking tutorials, cybersecurity study notes, tech for everyone, programming squirrel, inclusive cybersecurity"]
baseurl: ""
url: "https://the-programming-squirrel.com" 
permalink: pretty
theme: jekyll-squirrel-theme

# Author Details
author:
  name: Nyki Anderson
  avatar: /assets/avatars/avatar-white-buttonup.png
  bio: >
    Passionate cybersecurity advocate, empowering women & beginners with fun, accessible resources to crack the code & thrive in the field! 

# Squirrel Theme Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-glossary_tooltip
  - jekyll-toc
  - jekyll-figure
  - jekyll-paginate-v2

# Syntax Highlighting
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

jekyll-figure:
  paragraphs: false

pagination:
  enabled: true
  path: "/blog/page:num/"
  per_page: 5
  limit: 0
